name: Setup RDP on Windows

on: 
  push:
    branches:
      - main

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Set up RDP environment
      shell: pwsh
      run: |
        # Define username and password
        $username = "rdpuser"
        $password = "mypassword"

        # Create a new user
        net user $username $password /add
        net localgroup administrators $username /add

        # Enable Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

        # Allow RDP through Windows Firewall
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        # Display the IP Address
        $rdp_ip = (Invoke-RestMethod ifconfig.me)
        Write-Host "RDP is enabled. Connect using the following details:"
        Write-Host "IP Address: $rdp_ip"
        Write-Host "Username: $username"
        Write-Host "Password: $password"

        # Optional: Keep the session alive for a certain period (e.g., 60 minutes)
        Start-Sleep -Seconds 3600
        Write-Host "Session will terminate after 60 minutes."
