name: Windows - Anydesk RDP

on:
  workflow_dispatch:

jobs:
  build:
    name: Built Connection
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Set Up Environment
        run: |
          choco install anydesk -y --ignore-checksums --force --no-progress --pre
          pip install pyautogui --quiet
          pip install psutil --quiet

      - name: Download Files and Run
        run: |
          curl -s -L -o time.py https://your-direct-url/timelimit.py
          curl -s -L -o shutdown.bat https://your-direct-url/shutdown.bat
          curl -s -L -o C:\Users\Public\Desktop\Telegram.exe https://telegram.org/dl/desktop/win64
          curl -s -L -o C:\Users\Public\Desktop\Winrar.exe https://www.rarlab.com/rar/winrar-x64-621.exe
          powershell -Command "Invoke-WebRequest 'https://github.com/chieunhatnang/VM-QuickConfig/releases/download/1.6.1/VMQuickConfig.exe' -OutFile 'C:\Users\Public\Desktop\VMQuickConfig.exe'"
          
          # Install Telegram and WinRAR, then remove installers
          C:\Users\Public\Desktop\Telegram.exe /VERYSILENT /NORESTART
          del C:\Users\Public\Desktop\Telegram.exe
          C:\Users\Public\Desktop\Winrar.exe /S
          del C:\Users\Public\Desktop\Winrar.exe
          
          # Clean up Desktop shortcuts
          del /f "C:\Users\Public\Desktop\Epic Games Launcher.lnk" > errormsg.txt 2>&1
          del /f "C:\Users\Public\Desktop\Unity Hub.lnk" > errormsg.txt 2>&1

      - name: Set Password and Timezone
        run: |
          set password=@#Disala123456
          powershell -Command "Set-LocalUser -Name 'runneradmin' -Password (ConvertTo-SecureString -AsPlainText '%password%' -Force)"
          reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel" /v "{20D04FE0-3AEA-1069-A2D8-08002B30309D}" /t REG_DWORD /d 0 /f
          tzutil /s "Sri Lanka Standard Time"

      - name: Time Counter
        run: Start-Sleep -Seconds 21600
