name: Free Windows RDP

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Set up RDP environment
      run: |
        echo "Starting RDP on Windows Runner..."
        
        # Display CPU and RAM Information
        echo "System Information:"
        Get-ComputerInfo -Property CsName, OsName, WindowsVersion, OsArchitecture
        echo "CPU Information:"
        Get-WmiObject Win32_Processor | Select-Object Name, NumberOfCores, NumberOfLogicalProcessors
        echo "Memory Information:"
        Get-WmiObject Win32_OperatingSystem | Select-Object TotalVisibleMemorySize, FreePhysicalMemory
        
        # Create a user
        net user rdpuser mypassword /add
        net localgroup administrators rdpuser /add

        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # Fetch and display the IP of the current runner
        $rdp_ip = (Invoke-RestMethod ifconfig.me)
        echo "RDP IP: $rdp_ip"
        
        # Extend session timeout for better testing duration
        reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" /v MaxIdleTime /t REG_DWORD /d 0 /f
        
        echo "Setup complete, connect via RDP with IP: $rdp_ip, User: rdpuser, Password: mypassword"

        # Keep the session alive for a specified duration (e.g., 3600 seconds or 60 minutes)
        $duration = 3600 # Duration in seconds
        echo "Keeping the RDP session alive for $duration seconds..."
        Start-Sleep -Seconds $duration
        
        echo "RDP session is terminating after $duration seconds."
